.deploy_standup_k8s: &deploy_stand_up
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  script:
    - envsubst < k8s/ingress.yml > k8s/ingress-standup.yml
    - envsubst < k8s/deployment.yml > k8s/deployment-standup.yml
    - envsubst < k8s/service.yml > k8s/service-standup.yml
    - envsubst < k8s/certificate.yml > k8s/certificate-standup.yml
    - kubectl apply -f k8s/certificate-standup.yml -n standup-$NAMESPACE
    - kubectl apply -f k8s/deployment-standup.yml -n standup-$NAMESPACE
    - kubectl apply -f k8s/service-standup.yml -n standup-$NAMESPACE
    - kubectl apply -f k8s/ingress-standup.yml -n standup-$NAMESPACE
  allow_failure: false

.deploy-standup-k8s-feature:
  <<: *deploy_stand_up
  before_script:
  - HASH_BRANCH_NAME=$(printf "$CI_COMMIT_REF_NAME" | sha1sum | cut -c1-5)
  - export INGRESS_ENVIRONMENT_PREFIX=$HASH_BRANCH_NAME.
  - export HASH_BRANCH_NAME=-$HASH_BRANCH_NAME


.deploy-standup-k8s-master:
  <<: *deploy_stand_up

.deploy-standup-k8s-preprod:
  <<: *deploy_stand_up

.deploy-standup-k8s-prod:
  <<: *deploy_stand_up
